### ISSUE TITLE
"Syntax of file or directory name incorrect" error when syncing

### ISSUE THREAD

**Issue by giovi321** [aykit/MyOwnNotes#105]
If I create a new note on my windows computer and save it as a txt file, when I modify it with myownnotes app on my phone, the windows owncloud client doesn't sync that note due the following error: "Syntax of file or directory name incorrect".
Same problem with notes created with the software "QOwnNotes" (www.bekerle.com/QOwnNotes). Once the notes created with notepad or with QOwnNotes are modified with myownnotes app, they are no longer synced with the windows client.

**Comment by ramschmaerchen** [comment]
Good to know! We will try to fix it asap. However, we don't have much time at the moment. So asap could be longer than expected unfortunately

**Comment by giovi321** [comment]
Let me point out that the problem occurs only when you type a new line on the myownnotes app. If you modify the file without adding new lines no problems occur.

**Comment by giovi321** [comment]
Any news on this bug?

**Comment by ramschmaerchen** [comment]
Dear @giovi321 , we are currently working on Version 2.0 which should be released tomorrow. Bug should be fixed by then.

**Comment by giovi321** [comment]
Thank you! This is very good news. I'll test it as soon as it is released.

**Comment by giovi321** [comment]
Hi @ramschmaerchen, any news for version 2.0?

**Comment by maltefiala** [comment]
Dear @giovi321 , unfortunately, we were not able to finish 2.0 this weekend. We were neither able to fix this bug in 1.6, but we are working on it. Sorry for the delay.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
