### ISSUE TITLE
notepad.exe and EOL

### ISSUE THREAD

**Issue by yasuoiwakura** [aykit/MyOwnNotes#107]
Hi there,

MyOwnNotes is a very nice idea, i use it on BlackBerry 10OS.
However, when opening the Notes with notepad.exe (default windows text editor) i cannot see the LineBreak.
When opening with wordpad its OK but i will not change the default editor for .txt files and MyOwnNotes only accepts .txt as notes.

feature request:
- change default EOL char or let user decide wich one to use
  or
- accept other files names beside .txt
  or
- any other solution? :)

**Comment by maltefiala** [comment]
Dear @yasuoiwakura,
my own notes is an android application. Are you talking about my own notes or about owncloud notes? You find the owncloud notes application here: https://github.com/owncloud/notes

**Comment by yasuoiwakura** [comment]
hi maltefiala!
Yes its your application, BB10 can run most Android Applications.
regarding .txt files - do you have a windows machine with owncloud client? do you have a different behavior on the EOLs, is it maybe a Blackberry issue?

**Comment by giovi321** [comment]
Install Notepad 2 or Notepad++.
Do you have any issues when syncing notes created on your blackberry to your computer? Because I do, and it's a problem due to EOL on my BB Passport.

**Comment by maltefiala** [comment]
We will be working on My Own Notes during the osce days 2015 in Vienna. If you or someone else owning a black berry is there, we would be happy to try it out. Unfortunately, we don't own a BB ourselves and therefore can't provide any support for it.

**Comment by ramschmaerchen** [comment]
Unfortunately there is nobody with a BB in my circle

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
