### ISSUE TITLE
Self-signed certificate not working

### ISSUE THREAD

**Issue by driminicus** [aykit/MyOwnNotes#110]
I’m trying to get myownnotes working with my owncloud install.
I’ve installed ownnotes on my server (which works) but the app on my android keeps telling me that I’m trying to use a self-signed certificate.
I added my self-signed certificate to the android keychain and syncing using webdav (davdroid) works with this certificate.

Here’s what I think is the relevant part of logcat:
 
D/DOWNLOADTASK(17772): url:https://*serverIPhere*/owncloud/index.php/apps/notes/api/v0.2/notes
I/Timeline(17772): Timeline: Activity_idle id: android.os.BinderProxy@41f18bd0 time:15891880
I/ActivityManager(  939): Displayed org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity: +166ms
W/System.err(17772): javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5f48c7b8: Failure in SSL library, usually a protocol error
W/System.err(17772): error:1407743E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:744 0x5d884cf8:0x00000000)
W/System.err(17772):    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
W/System.err(17772):    at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
W/System.err(17772):    at com.android.okhttp.Connection.connect(Connection.java:107)
W/System.err(17772):    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
W/System.err(17772):    at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
W/System.err(17772):    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
W/System.err(17772):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
W/System.err(17772):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
W/System.err(17772):    at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
W/System.err(17772):    at org.aykit.owncloud_notes.NoteListActivity$DownloadNotesTask.doInBackground(NoteListActivity.java:1163)
W/System.err(17772):    at org.aykit.owncloud_notes.NoteListActivity$DownloadNotesTask.doInBackground(NoteListActivity.java:1129)
W/System.err(17772):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err(17772):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(17772):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(17772):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(17772):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(17772):    at java.lang.Thread.run(Thread.java:841)
W/System.err(17772): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5f48c7b8: Failure in SSL library, usually a protocol error
W/System.err(17772): error:1407743E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:744 0x5d884cf8:0x00000000)
W/System.err(17772):    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err(17772):    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
W/System.err(17772):    ... 16 more
E/NoteListActivity(17772): javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5f48c7b8: Failure in SSL library, usually a protocol error
E/NoteListActivity(17772): error:1407743E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:744 0x5d884cf8:0x00000000)
I/Timeline(  939): Timeline: Activity_windows_visible id: ActivityRecord{41a07b68 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity t35} time:15892351

**Comment by ramschmaerchen** [comment]
Please look at this issue, maybe it helps: https://github.com/aykit/myownnotes-android/issues/112

**Comment by driminicus** [comment]
Well, it turned out to be a certificate issue and I've created a new certificate. It works fine now. Thanks for the help!

**Comment by maltefiala** [comment]
You are welcome. Great you were able to fix it!
