### ISSUE TITLE
Connexion Error using MyOwnnotes 1.6

### ISSUE THREAD

**Issue by nytche** [aykit/MyOwnNotes#116]
Hello,
I have a connexion error using MyOwnNotes 1.6 with CyanogenMod 10.1, equivalent to Jelly Beans. Is there a way to make it work without KitKat version?
PS. previously, all worked fine.

**Comment by maltefiala** [comment]
Dear @nicocans :

MyOwnNotes is working fine on my Android 5.0 and as far as I know, it should do fine on Android 5.1 too. We need a bit more information. Please look at https://github.com/aykit/MyOwnNotes/blob/master/CONTRIBUTING.rst#user-content-how-to-submit-bugs-issues

First thing that comes to my mind:
Please make sure you migrated your self signed certificate (if any) to your new operating system.

**Comment by nicocans** [comment]
My server have no changed and have startssl certificate.
owncloud: 8.0.4
ownNotes: 1.0
encryption: no.
cyanogenmod: 10.1
Myownnotes: 1.6
I enabled LogCat, but did not find /data/anr/traces.txt ...

**Comment by maltefiala** [comment]
@steppenhahn Did you by any chance try it with Cyanogen 10.1?

**Comment by nicocans** [comment]
yes, it was the same phone too.

**Comment by maltefiala** [comment]
@nicocans Do you really mean 10.1 or are you talking about 12.1, the latest release?

**Comment by steppenhahn** [comment]
i have never tested MyOwnNotes on 10.1.
will try and test it on a virtual device next time. although i'm not quite sure how to get cyanogenmod onto a virtual device yet :)

but on 12.1 it works normally.

**Comment by nicocans** [comment]
I use cyanogenmod 10.1 on an old smartphone.
I mentioned it on my first post because android version is a requirement to use new versions of myOwnNotes. Is that true? can the issue come from another misconfig?

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
