### ISSUE TITLE
[Feature request] Widget for the android app 

### ISSUE THREAD

**Issue by mulles** [aykit/MyOwnNotes#120]
As for the app https://github.com/atd/HandyNotes  

I would find it useful to have a widget to take notes which are right away uploaded to owncloud instance as it is now already the case, thx to the amazing work of you :) 

See here for an illustrating example: 
https://e1000.atria.uberspace.de/owncloud/index.php/s/PWHeTwYPKBVwCAZ

maybe it is straight forward and the code of HandyNotes can be reused?!

**Comment by jancborchardt** [comment]
Hey @mulles, this is a duplicate of issue https://github.com/aykit/MyOwnNotes/issues/38 – let’s continue there. :)

**Comment by ramschmaerchen** [comment]
Dear @jancborchardt , thanks for referring!
