### ISSUE TITLE
TLSv1.2 support missing

### ISSUE THREAD

**Issue by evildead45** [aykit/MyOwnNotes#121]
Recently I changed my webserver configuration so that TLSv1.2 is the only protocol being offered. In the very same moment MyOwnNotes starts complaining about a self-signed certificate.

If I revert the configuration on the webserver so that it also offers TLSv1.0 all is fine again.

**Comment by grandiego** [comment]
4 days trying to make owncloud notes work, to finally find this issue. Could have spent years to figure this out.
Had to re-enable TLSv1.0 in my server.

Please add support for TLSv1.2

**Comment by evildead45** [comment]
As I opened the same ticket also at fdroid, here is there solution: https://gitlab.com/fdroid/fdroidclient/issues/370

Maybe this helps.

Best regards

**Comment by maltefiala** [comment]
Thanks for the input. Reference for development: https://gitlab.com/fdroid/fdroidclient/commit/2c88703588a6192cbf3ffd7ccb8d01b65c693ed3

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
