### ISSUE TITLE
How to add gradle dependency

### ISSUE THREAD

**Issue by Neha--Agarwal** [aykit/MyOwnNotes#122]
This project is not gradle based. I want to contribute to the UI but I need to add a gradle dependency for it. How shall I proceed?

**Comment by maltefiala** [comment]
Dear @Neha--Agarwal ,
it would be great to see you contributing. Master branch (Version 1.6) won't be ported to gradle. Development branch (version 2.0) already is gradle based. Please keep in mind that Version 2 needs a lot of attention. Version 2 is a rewrite and will feature a complete different UI. Best to ask @steppenhahn what needs to be done.

**Comment by Neha--Agarwal** [comment]
Thanks for the response @maltefiala . I built the development branch but its not even running on emulator. May I resolve that issue or is it intended? Sorry I'm new to this project so I need some clarifications.

**Comment by maltefiala** [comment]
Not building atm as far as I know. Although we had hoped otherwise, 2.0 is in it's very early stages atm.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
