### ISSUE TITLE
error syncing

### ISSUE THREAD

**Issue by geekpete** [aykit/MyOwnNotes#123]
Getting this error still:

Not getting correct JSON from server. Server OK?

ownCloud 8.1.3 (stable)

**Comment by steppenhahn** [comment]
are you using the server app "Notes" by Bernhard Posselt and Jan-Christoph Borchardt?
if not - problem right there.
myownnotes only works with this app.
you have to enable and use it in order to use myownnotes

**Comment by improti** [comment]
As I got confused by this, take note (lol) that "Notes" (https://github.com/owncloud/notes) is a different server-side app than "OwnNotes" (https://github.com/Fmstrat/ownnote). This Android app only works with Notes and not with OwnNotes.

**Comment by geekpete** [comment]
Perfect! Works a treat.

Now I can start thinking about an Evernote migration script...
