### ISSUE TITLE
Accept self-signed cert

### ISSUE THREAD

**Issue by NuxRo** [aykit/MyOwnNotes#125]
Hello,

Please accept self-signed certs (just like the ownCloud app does). 
I'm yet to find a way to install the self-signed cert in my Cyanogenmod 12.1 and the suggested howto does not work. I don't want to be running my own CA, I'm using self-signed just for encryption.

**Comment by piwats** [comment]
Same here

**Comment by fmikker** [comment]
@NuxRo One way that benefits both your security and your wallet is to try letsencrypt.org
It's a free CA with pretty easy installation of the certificates.

**Comment by NuxRo** [comment]
Well, that's in the future, this is now. :)

**Comment by maltefiala** [comment]
Future is here ;)
