### ISSUE TITLE
Cannot find notes in a sub-folder

### ISSUE THREAD

**Issue by lister171254** [aykit/MyOwnNotes#128]
I've created notes in a subfolder 'OldNotes' of the folder 'Notes'

When running MyOwnNotes on my Samsung tablet, I cannot get to that subfolder or see the notes in that folder. There doesn't seem to be any way of setting the root folder when setting up (or using) MyOwnNotes.

I can create a new note, which ends up in the Notes folder

Thankas

**Comment by maltefiala** [comment]
Dear @lister171254 : MyOwnNotes uses the https://github.com/owncloud/notes API (https://github.com/owncloud/notes/wiki/API-0.2) which unfortunately does not support subfolders.
