### ISSUE TITLE
how do I sync?

### ISSUE THREAD

**Issue by enoch85** [aykit/MyOwnNotes#129]
Hi!

Thanks for a great app.

What I wonder is how to sync from mobile. It's not obvious what address you should put in the field. Right now I have https://example.se/remote.php/caldav I've also tried with /webdav at the end but with no luck - it says connection error.

**Comment by maltefiala** [comment]
We are currently using the notes API. However, this will be changed with release of 2.0 that's right around the corner. https://github.com/owncloud/notes/wiki/API-0.2

**Comment by enoch85** [comment]
Ok thanks, but question remians how do I connect? Which address do I write?

**Comment by steppenhahn** [comment]
as mentioned in the short FAQ in the app under "help" you just need to enter the root URL to your server e.g: https://myserver.com
make sure to write the https though!

**Comment by enoch85** [comment]
Yeah, problem is, that doesn't work.

**Comment by tdwyer** [comment]
Yep, dose not work here ether.

https://example.com:2222 # no connect
https://example.com:2222/ # no connect
https://example.com:2222/index.html # this gives me invalid JSON
https://example.com:2222/index.html/index.php # invalid JSON
https://example.com:2222/index.html/index.php/apps/ownnote/ # this gives me invalid JSON

**Comment by tdwyer** [comment]
OwnCloud 9.0.2

**Comment by Matthias84** [comment]
Same here for OC 8.2.5 and ON 1.08. Corresponding to logcat the server returns plain HTML instead of JSON. Is there an easy way to get the URL that the App triggers?

**Comment by g4bb4j03** [comment]
Hi,
For me  the android app v1.6 is working fine with my owncloud 9.0.2 server and noteapp 2.0.1. Can you connect via other applications to your owncloud server, bsp. desktop client, mobile owncloud client? If you have with other applications too issues then is you owncloud server installation not done properly. I had with my firdt owncloud server installation once a similar issue. That was caused by a wrong vhost configuration of my apache that the main .htaccess file from the owncloud server was present but not proceed by apache so the rewrite rules etc where not working. Maybe you have in some way a similar issue.
Best regards,
Gabbajoe

**Comment by sfurey** [comment]
I've run into this as well. 

I'm running the 1.6 android app and Nextcloud 10. owncloudNotes for Android also works. QOwnNotes on multiple machines work just fine.

Relevant log lines

```
x.x.x.x - shaun [16/Sep/2016:11:17:25 -0400] "GET /nextcloud/index.php/apps/notes/api/v0.2/notes HTTP/1.1" 302 5 "-" "Dalvik/2.1.0 (Linux; U; Android 7.0; Nexus 6P Build/NRD90T)"
x.x.x.x - shaun [16/Sep/2016:11:17:26 -0400] "GET /nextcloud/index.php/apps/files/ HTTP/1.1" 200 37274 "-" "Dalvik/2.1.0 (Linux; U; Android 7.0; Nexus 6P Build/NRD90T)"
x.x.x.x - shaun [16/Sep/2016:11:17:34 -0400] "GET /nextcloud/index.php/apps/notes/api/v0.2/notes HTTP/1.1" 302 5 "-" "Dalvik/2.1.0 (Linux; U; Android 7.0; Nexus 6P Build/NRD90T)"
x.x.x.x - shaun [16/Sep/2016:11:17:35 -0400] "GET /nextcloud/index.php/apps/files/ HTTP/1.1" 200 37274 "-" "Dalvik/2.1.0 (Linux; U; Android 7.0; Nexus 6P Build/NRD90T)"
```

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed

**Comment by pbek** [comment]
@maltefiala, great will it be on the google play store?

**Comment by maltefiala** [comment]
Current Roadmap:
* Fix F-Droid problem (does not auto-build atm)
* Hear some voices of F-Droid and open source users (bugs?)
* Release update to 2.0 on play store

**Comment by pbek** [comment]
Thanks for the feedback, I can't wait to test it! ;)

**Comment by pbek** [comment]
Disclaimer: I'm the author of https://github.com/pbek/QOwnNotes :smile_cat:

**Comment by maltefiala** [comment]
Great, good to know!
