### ISSUE TITLE
Failure retrieving resources for org.aykit.MyOwnNotes

### ISSUE THREAD

**Issue by ssdnvv** [aykit/MyOwnNotes#130]
Hi,

I just downloaded your app.
After setting app owncloud notes on my server I entered the url and credentials into the app.
The app then shows the Notes, but when I edit a file, It shows an "update" on the right to the note and then a toast message pops up saying a connection failure occured.
Looking into logcat it shows the following lines linked to the search for myownnote

---

02-20 19:30:42.458 I/Timeline(4666): Timeline: Activity_launch_request id:org.aykit.MyOwnNotes time:185695
02-20 19:30:42.519 I/ActivityManager(3853): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity bnds=[182,504][360,704]} from uid 10112 on display 0
02-20 19:30:42.536 V/WindowManager(3853): addAppToken: AppWindowToken{bf5c908 token=Token{ac24eab ActivityRecord{2ceaa8fa u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity t648}}} to stack=1 task=648 at 0
02-20 19:30:42.629 I/ActivityManager(3853): Start proc 9086:org.aykit.MyOwnNotes/u0a356 for activity org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity
02-20 19:30:42.669 V/WindowManager(3853): Adding window Window{354dac49 u0 Starting org.aykit.MyOwnNotes} at 2 of 8 (after Window{3ab2ff62 u0 com.android.settings/com.android.settings.Settings})
02-20 19:30:42.775 W/XPrivacy(9086): Hooking package=org.aykit.MyOwnNotes
02-20 19:30:43.064 V/WindowManager(3853): Adding window Window{3b2272d6 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity} at 3 of 9 (before Window{354dac49 u0 Starting org.aykit.MyOwnNotes})
02-20 19:30:43.445 I/ActivityManager(3853): Displayed org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity: +895ms
02-20 19:30:43.448 I/Timeline(3853): Timeline: Activity_windows_visible id: ActivityRecord{2ceaa8fa u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity t648} time:186685
02-20 19:30:49.301 V/WindowManager(3853): Adding window Window{1602a349 u0 com.estrongs.android.pop/com.estrongs.android.pop.app.UninstallMonitorActivity} at 4 of 9 (after Window{3b2272d6 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity})
02-20 19:31:21.678 W/PackageManager(4096): Failure retrieving resources for org.aykit.MyOwnNotes: Resource ID #0x0
02-20 19:31:22.750 W/PackageManager(4096): Failure retrieving resources for org.aykit.MyOwnNotes: Resource ID #0x0
02-20 19:31:34.788 V/WindowManager(3853): Adding window Window{2d6635db u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity} at 5 of 10 (after Window{3b2272d6 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity})

---

I can edit the files without any problems within owncloude itself (just stating this as my initial thought was, that owncloud itself could have an issue).
Those notes have been created with the windows application quickeditor (http://quickeditor.ranger81.de/) and uploaded to the notes-foldes via the official owncloud sync.

Kind regards,
ssdnvv

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
