### ISSUE TITLE
Custom folder

### ISSUE THREAD

**Issue by demlak** [aykit/MyOwnNotes#131]
hi,
since i'm using QOwnnotes a lot and since i'm using a custom folder in it, i would like to ask for an option in MyOwnNotes to change default notesfolder.. 

it's not realy necessary, because i'm able to change the folder in QOwnNotes.. but i would like to have my "_notes" instead of "notes" folder... because of sorting in webdav browsers =)

i'm not sure if this is just a QOwnNotes feature.. and/or if this is possible with the default notes api.

thx in advance

**Comment by maltefiala** [comment]
Won't fix
