### ISSUE TITLE
Die Url, von der Daten abgefragt werden, scheint nicht zu existieren.

### ISSUE THREAD

**Issue by naraesk** [aykit/MyOwnNotes#132]
Hello,

when syncing notes I get the following error message: "Die Url, von der Daten abgefragt werden, scheint nicht zu existieren." What to do? The url is correct of course. I'm running owncloud 9 and the corresponding version of the notes app. Might this cause the problem?

Thanks in advane. :-)

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
