### ISSUE TITLE
Latest Version? 

### ISSUE THREAD

**Issue by cengbrecht** [aykit/MyOwnNotes#134]
I currently have version 1.0.0 installed, but I am unable to connect to the notes from the app.
Nothing's changed, and I can see notes from the wan side. But not in the app. Any advice?

**Comment by cengbrecht** [comment]
Is this android app compatible with owncloud/notes?

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
