### ISSUE TITLE
Can't connect to my server

### ISSUE THREAD

**Issue by aizikil** [aykit/MyOwnNotes#135]
Hi, so as I mentioned above, I can't connect to my server. I made a self signed certificate and I don't use domain name, so my server address string is "https//195.144.**_.**_:8006" (note that port isn't standard). Certificate is imported to my mobile phone and when app tries to connect to server it popups a message which says that - "The URL you request data from doesn't seem to exist......."

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
