### ISSUE TITLE
[Android app] Json error

### ISSUE THREAD

**Issue by anonymeuh** [aykit/MyOwnNotes#137]
Please help us by providing the following info.

[b]Steps to reproduce[/b]
1. Installing the app Myownnotes v1.6 or Notes v0.9.0
2. Trying to login to my owncloud server with good IDs

[b]Expected behaviour[/b]
I expected it to login and synchronizes my notes with my owncloud server.

[b]Actual behaviour[/b]
Error JSON, no synchronization, no login.

[b]Mobile client configuration[/b]
Client OS (iOS, Android, ...): Android 6.0
Client version: Myownnotes v1.6 or Notes v0.9.0

[b]Server configuration[/b]
Operating system: Debian Jessie
Web server: Nginx
Database: Mariadb
PHP version:7.0
ownCloud version (see ownCloud admin page): 9.1.1
Updated from an older ownCloud or fresh install:fresh install

**Comment by Rowabi** [comment]
New installation of MyOnwNotes.
I get an Error message:  "Kein gültiges JSON Fomat vom Server bekommen. Server OK?"
"Englisch: No valid JSON Format received from the Server."
Connection with the Owncloud App works fine
Owncloud Version 9.1.3
Ownnote by Ben Curtis is activated
Client Samsung Note 8.0 / Android 4.4.2
What can I do to solve this?
Thanks

**Comment by gerribaldi** [comment]
Same Problem with nexus 5 and android 6.0.1 and shield tablet with android 6, owncloud 9.1.2
Any hints?

**Comment by x86dev** [comment]
Same here. NextCloud 11 with QOwnNotes API installed. QOwnNotes on the desktop works flawless, but with MyOwnNotes on Android 6.0.1 I also get the "JSON Error".

**Comment by Yeru-314** [comment]
Same here. OC 8.2 and an Android 5.1.1

**Comment by avamk** [comment]
Same here with ownCloud 9.1.4 and Android 5. Please help!

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
