### ISSUE TITLE
Specific user can't sync notes (admin can)

### ISSUE THREAD

**Issue by dstu69** [aykit/MyOwnNotes#138]
These are the logs I get in /data/owncloud.log when the connection is rejected for that user:
`{"reqId":"WlQOedGNoG\/5Hg67jfIJ","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/node.php(338): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/notes\\\/service\\\/notesservice.php(50): OC\\\\Files\\\\Node\\\\Node->getType()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/notes\\\/controller\\\/notesapicontroller.php(77): OCA\\\\Notes\\\\Service\\\\NotesService->getAll('2nduser')\\n#3 [internal function]: OCA\\\\Notes\\\\Controller\\\\NotesApiController->index('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Notes\\\\Controller\\\\NotesApiController), 'index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Notes\\\\Controller\\\\NotesApiController), 'index')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('NotesApiControl...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(283): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(877): OC\\\\Route\\\\Router->match('\\\/apps\\\/notes\\\/api...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(48): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/node.php\",\"Line\":82}","level":4,"time":"2016-11-19T17:16:02+02:00"}
{"reqId":"WlQOedGNoG\/5Hg67jfIJ","remoteAddr":"x.x.x.x","app":"PHP","message":"Exception: Session has been closed - no further changes to the session as allowed at \/var\/www\/owncloud\/lib\/private\/session\/internal.php#109","level":3,"time":"2016-11-19T17:16:02+01:00"}`

I checked the /var/www/owncloud/data/2nduser/files/Notes folder and there's only one note that i created through the web interface. The file's and folder's permissions and owners are identical to my admin user's notes files/folders.

Any suggestion?

Thanks in advance,

David

**Comment by dstu69** [comment]
I just added another user and created a note for it using the app, and it works, so it's only for that specific user that something happened, but I have no idea how to resolve it. I enabled in the app the `extensive logcat output` option, but I can't find any logs on the phone

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
