### ISSUE TITLE
Version 2 not on F-Droid

### ISSUE THREAD

**Issue by maltefiala** [aykit/MyOwnNotes#139]
Build problems with version 2 on F-Droid. I will fix it.

**Comment by Yeru-314** [comment]
(First off: Thx for the new release and solving #137 .)
Even when I try to to build the .apk by myself according to the instructions in the readme, I get 
"Error:A problem occurred configuring project ':app'.
Failed to find target with hash string 'android-23' in: /home/<user>/Android/Sdk"
Any ideas?

**Comment by maltefiala** [comment]
We don't have any build instructions in the README: https://github.com/aykit/MyOwnNotes/blob/master/README.rst

**Comment by ramschmaerchen** [comment]
Merge is pending: https://gitlab.com/fdroid/fdroiddata/merge_requests/2120

**Comment by ramschmaerchen** [comment]
Merge complete, we are waiting for F-Droid to update its builds and metadata: https://f-droid.org/wiki/page/org.aykit.MyOwnNotes

**Comment by gardar** [comment]
It's live on F-droid, just got the update!
https://f-droid.org/repository/browse/?fdfilter=myownnotes&fdid=org.aykit.MyOwnNotes

**Comment by ramschmaerchen** [comment]
Yes!
