### ISSUE TITLE
Cannot logon to owncloud server

### ISSUE THREAD

**Issue by peteman52** [aykit/MyOwnNotes#147]
Hi,
my server configuration:
OwnCloud version: 9.1.5.2
server OS: Linux
ownNote 1.0.8
kind of server address:  https://myserver:port/owncloud

my android:
6.0.1, security patch 01.09.2016

This does make the MyOwnNotes App think of wrong username or password when trying to login ("Please check your username and password.").
username is shown as username@myserver:port/owncloud

problem seems related to #145, #146

**Comment by peteman52** [comment]
sorry, forgot to mention: MyOwnNote app 2.0

**Comment by peteman52** [comment]
Issue solved with ownCloud Synchronization client 2.4.0

**Comment by osilvab** [comment]
Using ownCloud synchronization client 2.5.0 the issue happens. also with 2.4.0
