### ISSUE TITLE
Anybody out there?

### ISSUE THREAD

**Issue by peteman52** [aykit/MyOwnNotes#148]
Hello, are the maintainers all drunk or dead? Or is the project dead?

**Comment by ramschmaerchen** [comment]
Hopefully drunk.

Things don't fix themselves. I'd be happy to pull your PRs.

**Comment by pecuna** [comment]
No one is writing anymore. MyOwnNotes 1.6 is not working with NC 12 and Notes 2.2.0 and above. Cant sync at all - everytime I got "There was a connection error"...

**Comment by peteman52** [comment]
Maybe this will help you: https://github.com/aykit/MyOwnNotes/issues/147
