### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by jancborchardt** [aykit/MyOwnNotes#18]
Instead of having a dedicated refresh button, it would be better to implement the well-known pull-to-refresh pattern.

**Comment by ramschmaerchen** [comment]
Fixed

**Comment by jancborchardt** [comment]
@ramschmaerchen oooh awesome! Good to see you’re working on the app again! :)

Since it has been some time – is it also compatible with https://nextcloud.com (community-driven fork of ownCloud), or is there anything we can help with making it work? :)

**Comment by ramschmaerchen** [comment]
Hej @jancborchardt , see https://github.com/aykit/MyOwnNotes/issues/140
