### ISSUE TITLE
Don’t show keyboard immediately for existing notes

### ISSUE THREAD

**Issue by jancborchardt** [aykit/MyOwnNotes#22]
It’s good to show the keyboard immediately for new notes – because you can only type. But existing notes you first probably want to read, and if you want to edit also first scroll to the point where you want to edit them.

Hence for existing notes, the keyboard should not be shown immediately but only once the content area is tapped.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
