### ISSUE TITLE
List often blank

### ISSUE THREAD

**Issue by jancborchardt** [aykit/MyOwnNotes#24]
Often when I open the app, the list is shown as blank. This also happens during manual refreshes and is very annoying – to the point where I continuously think the app deleted my data. This leads to doubting the app and a not-so-good experience.

Instead the list should always show the last known good state between refreshes, and never be blank – unless there’s actually no data there.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
