### ISSUE TITLE
Widget [feature request]

### ISSUE THREAD

**Issue by DPTJKKVH** [aykit/MyOwnNotes#38]
As far as I can tell the app has no widget. I'd love to see a widget that displays only the titles, opens a note by tapping on a title and allows to create a new note by pressing a plus button on the upper right corner.

**Comment by ramschmaerchen** [comment]
This is not on our roadmap for 2015. However, we'd be happy to have someone doing it. A [bounty](https://www.bountysource.com) might convince someone to do it...

**Comment by maltefiala** [comment]
We won't do this, closed.

**Comment by jancborchardt** [comment]
@ramschmaerchen @maltefiala one of the magic things of open source is that someone could contribute this. :) Especially since you rewrote the app now, I would advise keeping this open or opening a fresh issue and then put it up as »help wanted«.

**Comment by ramschmaerchen** [comment]
I have a deja vu.
