### ISSUE TITLE
ssl handshake

### ISSUE THREAD

**Issue by gityeti** [aykit/MyOwnNotes#62]
Thank you very match for the solution concerning the port (#44). It works out of the box ;-) and connexion is ok: This error doesn't appear anymore. But I have a problem with the self-signed-certificate, the phone can't read/find it.

$ adb logcat | grep -i NoteListActivity
- waiting for device -
  I/ActivityManager( 2222): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=org.aykit.MyOwnNotes cmp=org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity} from pid 11431
  I/ActivityManager( 2222): Start proc org.aykit.MyOwnNotes for activity org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity: pid=11910 uid=10007 gids={50007, 3003}
  I/ActivityManager( 2222): Displayed org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity: +1s887ms
  I/Timeline( 2222): Timeline: Activity_windows_visible id: ActivityRecord{41ba24b8 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity t185} time:178682236
  D/NoteListActivity(11910): starting note synchonization
  D/NoteListActivity(11910): writing new notes to server
  D/NoteListActivity(11910): writing modified notes to server
  D/NoteListActivity(11910): deleting notes from server
  D/NoteListActivity(11910): getting notes from server
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:854)
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:823)
  E/NoteListActivity(11910): ioException in UploadNotesTask:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:854)
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:823)
  E/NoteListActivity(11910): ioException in UploadNotesTask:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
  I/Timeline( 2222): Timeline: Activity_windows_visible id: ActivityRecord{41ba24b8 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity t185} time:178742781
  I/Timeline( 2222): Timeline: Activity_windows_visible id: ActivityRecord{41ba24b8 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity t185} time:178766524
  D/NoteListActivity(11910): starting note synchonization
  D/NoteListActivity(11910): writing new notes to server
  D/NoteListActivity(11910): writing modified notes to server
  D/NoteListActivity(11910): deleting notes from server
  D/NoteListActivity(11910): getting notes from server
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:854)
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:823)
  E/NoteListActivity(11910): ioException in UploadNotesTask:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:854)
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:823)
  E/NoteListActivity(11910): ioException in UploadNotesTask:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
  I/Timeline( 2222): Timeline: Activity_windows_visible id: ActivityRecord{41ba24b8 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity t185} time:180167355
  D/NoteListActivity(11910): starting note synchonization
  D/NoteListActivity(11910): writing new notes to server
  D/NoteListActivity(11910): writing modified notes to server
  D/NoteListActivity(11910): deleting notes from server
  D/NoteListActivity(11910): getting notes from server
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:854)
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:823)
  E/NoteListActivity(11910): ioException in UploadNotesTask:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:854)
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:823)
  E/NoteListActivity(11910): ioException in UploadNotesTask:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
  I/ActivityManager( 2222): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity} from pid 2563
  I/ActivityManager( 2222): Displayed org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity: +308ms
  I/Timeline( 2222): Timeline: Activity_windows_visible id: ActivityRecord{4283bf38 u0 org.aykit.MyOwnNotes/org.aykit.owncloud_notes.NoteListActivity t185} time:186981698
  D/NoteListActivity(11910): menu: start sync
  D/NoteListActivity(11910): starting note synchonization
  D/NoteListActivity(11910): basePath with port: xx.xxx.xx.xxx:8092/index.php/apps/notes/api/v0.2/notes
  D/NoteListActivity(11910): urlToConnect:https://xx.xxx.xx.xxx:8092/index.php/apps/notes/api/v0.2/notes
  D/NoteListActivity(11910): writing new notes to server
  D/NoteListActivity(11910): cursor rows new notes:2
  D/NoteListActivity(11910): writing modified notes to server
  D/NoteListActivity(11910): cursor rows modified notes:0
  D/NoteListActivity(11910): deleting notes from server
  D/NoteListActivity(11910): cursor rows to delete:0
  D/NoteListActivity(11910): getting notes from server
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:854)
  W/System.err(11910):    at org.aykit.owncloud_notes.NoteListActivity$UploadNotesTask.doInBackground(NoteListActivity.java:823)
  E/NoteListActivity(11910): ioException in UploadNotesTask:javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

I followed both howtos step by step
https://aykit.org/sites/myownnotes.html
https://support.google.com/nexus/answer/2844832?hl=en
When I go through, it prompts ' certificate is installed', but it doesn't appear in the list of 'Trusted Credentials' neither in the list of 'User'.
So the only question I found with no answer is : what should be the permissions of the certificate?
On my phone it is (ls -l)
 -rwxrwx---    root  sdcard_r   xxxxxxx.crt
Perhaps you could give me some hint...

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
