### ISSUE TITLE
Comodo SSL wildcard certificate incorrectly detected as self-signed

### ISSUE THREAD

**Issue by wiserweb** [aykit/MyOwnNotes#68]
If you have a wildcard certificate installed on the owncloud instance, i.e. *.example.com and you try to connect with MyOwnNotes the client will incorrectly detect that the site is using a self-signed certificate.

Other Android apps works as expected, such as CalDav apps with the signed certificate. This issue seems to be exclusive to myownnotes.

**Comment by ramschmaerchen** [comment]
Please look at this issue, maybe it helps: #112

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
