### ISSUE TITLE
auto-enable Notes app on server or warn

### ISSUE THREAD

**Issue by Cathryne** [aykit/MyOwnNotes#69]
I forgot to check if my ownCloud had the Notes app enabled at all, so I lost the note I created. There was no clear warning, just a generic "server OK?" message.

Would it be possible to implement an automatic activation of the app server-side, upon connection of MyOwnNotes?

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
