### ISSUE TITLE
Option for displayed lines per item

### ISSUE THREAD

**Issue by Isgar** [aykit/MyOwnNotes#70]
Currently there are always the first two lines visible for each item. I have quite a few notes and all of them are named, meaning the second line is quite distracting when trying to find the right note. I would like to only view the title ie. the first line in overview.

This was actually better for me when the first line was bold, but I understand it's against the design of the notes app which makes titles optional.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
