### ISSUE TITLE
Connection hostname not passed in HTTPS handshake/headers

### ISSUE THREAD

**Issue by rigrig** [aykit/MyOwnNotes#71]
My ownCloud server is set up with wildcard subdomains for virtual hosts:
* tubul.net is a plain html page, and the default host for non-matching servernames
* cloud.tubul.net is for ownCloud
* some_other_subdomains.tubul.net are also in use

When I try to sync using MyOwnNotes, it ends up connecting to the default tubul.net host, so fails to retrieve the notes, and shows a toast with "There was a connection error"

ownCloud server version: ownCloud 7.0.1 (stable) 
ownCloud Notes server version: Notes 0.9
ownCloud encryption plugin(enabled) version: Encryption0.6.1
Android version: 4.4.4 
CyanogenMod version: 11-20140804-SNAPSHOT-M9-ville
Apache version: Apache/2.2.22 (Debian)

As far as I can tell, SSL is setup correctly: https://www.ssllabs.com/ssltest/analyze.html?d=cloud.tubul.net
The certificate is for *.tubul.net, with alt names of *.tubul.net and tubul.net.

Manually opening https://cloud.tubul.net/index.php/apps/notes/api/v0.2/notes in a browser seems to work fine (as long as I'm already logged in), and shows the single note I've made as JSON. This is the exact URL that shows up in the logcat.
The ownCloud client, and CardDAV-Sync and CalDAV-Sync apps all work fine using https, MyOwnNotes seems to be the only app having troubles.

Apache log files for tubul.net: (nothing shows up in the cloud.tubul.net logs)
==> error.log <==
[Tue Aug 12 13:16:13 2014] [error] [client 82.75.154.138] request failed: error reading the headers
==> access.log <==
82.75.154.138 - - [12/Aug/2014:13:16:13 +0000] "GET /index.php/apps/notes/api/v0.2/notes HTTP/1.1" 400 715 "-" "-"

db logcat output, just after pressing the sync button: 
D/NoteListActivity( 5890): menu: start sync
D/NoteListActivity( 5890): starting note synchonization
D/NoteListActivity( 5890): basePath no port: cloud.tubul.net/index.php/apps/notes/api/v0.2/notes
D/NoteListActivity( 5890): urlToConnect:https://cloud.tubul.net/index.php/apps/notes/api/v0.2/notes
D/NoteListActivity( 5890): writing modified notes to server
D/NoteListActivity( 5890): cursor rows modified notes:0
D/NoteListActivity( 5890): deleting notes from server
D/NoteListActivity( 5890): cursor rows to delete:0
D/NoteListActivity( 5890): writing new notes to server
D/NoteListActivity( 5890): cursor rows new notes:0
D/NoteListActivity( 5890): getting notes from server
D/DOWNLOADTASK( 5890): url:https://cloud.tubul.net/index.php/apps/notes/api/v0.2/notes
E/NoteListActivity( 5890): error @ downloading notes. response code: 400

**Comment by ramschmaerchen** [comment]
We pushed version 1.6 with PR #108 today. There is a good chance it fixes that issue. Additonally, issue #112 gives some information about SSL handling in android

**Comment by rigrig** [comment]
Confirmed that the issue is fixed in 1.6

**Comment by ramschmaerchen** [comment]
Great, thanks a lot for your feedback!
