### ISSUE TITLE
connection to owncloud is not working (url not exists)

### ISSUE THREAD

**Issue by LotekHeavy** [aykit/MyOwnNotes#73]
HI;

I have a owncloud running on "https://www.domain.example/cloud" if I input this into the setup of your app (under server address), the notes are not getting synch'ed. 

the app says something about "url not found/exists".. (if I click on the sync/refresh icon). But I'm 100% sure that my cloud is working and I can read the notes online under those links:
- https://www.domain.example/cloud/index.php/apps/files?dir=%2FNotes
- https://www.domain.exeamplecloud/index.php/apps/notes/#/notes/84

I even tried to input the webdav folder (https://www.domain.exemple/cloud/remote.php/webdav/), but still not working ?!? Everything else (syncing with the official app, using davdroid for contacts, calendars, ..) is working.

Could it be a problem for your app that the cloud is running on a subdirectory (I have no choice in this case)

Thanks for any help!

**Comment by freibadschwimmer** [comment]
experience same issue, though on newer versions:



Same issue.

running OC 8.0.3, php 5.4, apache server on debian 7, certificate is added to key chain;
installed notes 1.0.0; can access it via webinterface, works fine in browser, but can't access from app (v1.5)

i copied the server address and username into the app settings, retyped passwd several times, so there shouldn't be spelling mistakes, yet i get the message, url not exists.

**Comment by maltefiala** [comment]
See this issue for more information about certificate management: #112

**Comment by freibadschwimmer** [comment]
Thank you for the hint; while I haven't considered that earlier, it didn't solve my problem. I still cannot connect to the server.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
