### ISSUE TITLE
Credential fields erased when connection was unsuccessful

### ISSUE THREAD

**Issue by jancborchardt** [aykit/MyOwnNotes#79]
Currently when you go back to confirm the settings and your credentials were wrong, the address, name and password fields will be wiped.

That shouldn’t happen – currently you have to type everything again if you had just one typo.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.

**Comment by jancborchardt** [comment]
@steppenhahn @maltefiala thanks a bunch for your work! :)
