### ISSUE TITLE
Keep scroll progress after refreshing

### ISSUE THREAD

**Issue by Isgar** [aykit/MyOwnNotes#84]
Following scenario:
I open the app or come back from editing a note and scroll down to find another note. Refresh finishes and I have to scroll again. That is really annoying and bad for usability. Waiting and then scrolling (or trying to be really fast if I know the note hasn't changed) isn't great either.

If scroll progress is kept the flow would be much better.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
