### ISSUE TITLE
Change default note title to avoid semicolumn

### ISSUE THREAD

**Issue by kai11** [aykit/MyOwnNotes#88]
By default note have format like yyyy-mm-dd hh:mm:ss  and time part will cause problems on some filesystems (NTFS).
Please change formatting to hh_mm_ss (as a quick fix) or let user select format as text (%Y-%m-%d %h_%I_%S, etc...)

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
