### ISSUE TITLE
App password secured

### ISSUE THREAD

**Issue by lowtower** [aykit/MyOwnNotes#92]
Hi,

I'd like to see the possibilty to secure the app with a password.

Cheers,
LT

**Comment by ramschmaerchen** [comment]
Well, this'd take a time... a long time. Sorry.

**Comment by giovi321** [comment]
There are external apps that allow to lock other apps with a password. I'm sure there is for BlackBerry 10, I would bet that there is for Android as well.

**Comment by ramschmaerchen** [comment]
I suggest you use Cyanogenmod and it's folder locking functionality

**Comment by moshpirit** [comment]
The official Owncloud app has a pass locker, can't be used here too?

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed.
