### ISSUE TITLE
Not obvious how to confirm account settings

### ISSUE THREAD

**Issue by jancborchardt** [aykit/MyOwnNotes#96]
It is not obvious at all that you have to go »back« out from the settings to confirm the account details. There should be some kind of »Confirm« button on the top right which also takes you back, but makes it clear that it confirms the details you just put in.

**Comment by ctgcwiqc** [comment]
I agree, should be a "test settings" or "confirm settings" to verify settings are correct prior to backing out of settings menu.

**Comment by maltefiala** [comment]
Yep, you are totally right, we'll change that.

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
