### ISSUE TITLE
First line of Note as Note name

### ISSUE THREAD

**Issue by TiberiusRegenschein** [aykit/MyOwnNotes#99]
First off all thanks for the great tool. I am using it on a daily basis.
With your latest release you introduced "First line of Note as Note name" Unfortunately this is not for users like me who are using more sophisticated editors when working from a desktop environment like e.g. zim-wiki because the first line is always the same property information of the .txt file. I went back to release 1.3.1.
My suggestion:
- Perfect would be the support of zim-wiki as there is no solution for Android yet
- It would also be ok for me to let me choose the type of Note naming in the setting dialogue. I would in that case stay with the old naming by file name.

Thanks and keep up the good work!

**Comment by ramschmaerchen** [comment]
Default title name being the date can be switched in the settings. Is that what you were referring to?

**Comment by LudovicRousseau** [comment]
The names of the notes on the web interface are the name of the files.
The names of the notes on the Android interface are the first line of the files.

It would be fine to keep the file names as notes names on Android.

**Comment by TiberiusRegenschein** [comment]
Your comment LudovicRousseau is absolutely correct.
In my case using zim-wiki as an advanced editor the first line of the note is always "Content-Type: text/x-zim-wiki" making every note showing the same name in android.

**Comment by ramschmaerchen** [comment]
Dedicated title in 2.0
